version: "3.1" 

services:

  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - ./cache:/var/cache/apt-cacher-ng
    restart: always
  
  ansible:
    build: ./ansible
    container_name: ansible
    tty: true
    stdin_open: true

    network_mode: host

    environment:
      DOCKER_HOST: "CaptainMcCrank.local" # Change to your hostname

    volumes:
      - /Users/Patrick/Development/Playbooks/DockerVolume:/home/pi/Playbooks # Change to your host OS's path for the Playbooks directory that you want to use.
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket # this is used for enabling mdns on linux systems.  Assumes Avahi is installed on host OS.  You shouldn't need to modify this on mac or windows based hosts.

volumes:
  apt-cacher-ng: